#ifndef APERY_PARAMETERS_HPP
#define APERY_PARAMETERS_HPP

#include "tt.hpp"

constexpr int FLOAT_SCALE = 1 << 10;

// [0, 256]
#ifndef QSEARCH_FUTILITY_MARGIN
#define QSEARCH_FUTILITY_MARGIN 128
#endif

// [2, 16]
#ifndef SEARCH_RAZORING_DEPTH
#define SEARCH_RAZORING_DEPTH 8 // 4 * OnePly
#endif

// [0, 32768]
#ifndef SEARCH_RAZORING_MARGIN_SLOPE
#define SEARCH_RAZORING_MARGIN_SLOPE 16384 // 16 * FLOAT_SCALE
#endif

// [0, 1048576]
#ifndef SEARCH_RAZORING_MARGIN_INTERCEPT
#define SEARCH_RAZORING_MARGIN_INTERCEPT 524288 // 512 * FLOAT_SCALE
#endif

// [2, 28]
#ifndef SEARCH_FUTILITY_MARGIN_DEPTH_THRESHOLD
#define SEARCH_FUTILITY_MARGIN_DEPTH_THRESHOLD 14 // 7 * OnePly
#endif

// [0, 138096]
#ifndef SEARCH_FUTILITY_MARGIN_LOG_D_COEFFICIENT
#define SEARCH_FUTILITY_MARGIN_LOG_D_COEFFICIENT 69048 // 67.43 * FLOAT_SCALE
#endif

// [0, 16384]
#ifndef SEARCH_FUTILITY_MARGIN_MOVE_COUNT_COEFFICIENT
#define SEARCH_FUTILITY_MARGIN_MOVE_COUNT_COEFFICIENT 8192 // 8 * FLOAT_SCALE
#endif

// [0, 136986]
#ifndef SEARCH_FUTILITY_MARGIN_INTERCEPT
#define SEARCH_FUTILITY_MARGIN_INTERCEPT 68493 // 66.888 * FLOAT_SCALE
#endif

// [2, 16]
#ifndef STATIC_NULL_MOVE_PRUNING_DEPTH_THRESHOLD
#define STATIC_NULL_MOVE_PRUNING_DEPTH_THRESHOLD 8 // 4 * OnePly
#endif

// [2, 8]
#ifndef SEARCH_NULL_MOVE_DEPTH_THRESHOLD
#define SEARCH_NULL_MOVE_DEPTH_THRESHOLD 4 // 2 * OnePly
#endif

// [0, 512]
#ifndef SEARCH_NULL_MOVE_REDUCTION_SLOPE
#define SEARCH_NULL_MOVE_REDUCTION_SLOPE 256 // 0.25 * FLOAT_SCALE
#endif

// [2, 12]
#ifndef SEARCH_NULL_MOVE_REDUCTION_INTERCEPT
#define SEARCH_NULL_MOVE_REDUCTION_INTERCEPT 6 // (3 * OnePly)
#endif

// [0, 180]
#ifndef SEARCH_NULL_MOVE_MARGIN
#define SEARCH_NULL_MOVE_MARGIN 90 // PawnScore
#endif

// [2, 24]
#ifndef SEARCH_NULL_MOVE_NULL_SCORE_DEPTH_THRESHOLD
#define SEARCH_NULL_MOVE_NULL_SCORE_DEPTH_THRESHOLD 12 // 6 * OnePly
#endif

// [2, 20]
#ifndef SEARCH_NULL_FAIL_LOW_SCORE_DEPTH_THRESHOLD
#define SEARCH_NULL_FAIL_LOW_SCORE_DEPTH_THRESHOLD 10 // 5 * OnePly
#endif

// [2, 20]
#ifndef SEARCH_PROBCUT_DEPTH_THRESHOLD
#define SEARCH_PROBCUT_DEPTH_THRESHOLD 10 // 5 * OnePly
#endif

// [0, 400]
#ifndef SEARCH_PROBCUT_RBETA_SCORE_DELTA
#define SEARCH_PROBCUT_RBETA_SCORE_DELTA 200
#endif

// [2, 16]
#ifndef SEARCH_PROBCUT_RBETA_DEPTH_DELTA
#define SEARCH_PROBCUT_RBETA_DEPTH_DELTA 8 // 4 * OnePly
#endif

// [2, 20]
#ifndef SEARCH_INTERNAL_ITERATIVE_DEEPENING_PV_NODE_DEPTH_THRESHOLD
#define SEARCH_INTERNAL_ITERATIVE_DEEPENING_PV_NODE_DEPTH_THRESHOLD 10 // 5 * OnePly
#endif

// [2, 32]
#ifndef SEARCH_INTERNAL_ITERATIVE_DEEPENING_NON_PV_NODE_DEPTH_THRESHOLD
#define SEARCH_INTERNAL_ITERATIVE_DEEPENING_NON_PV_NODE_DEPTH_THRESHOLD 16 // 8 * OnePly
#endif

// [0, 512]
#ifndef SEARCH_INTERNAL_ITERATIVE_DEEPENING_SCORE_MARGIN
#define SEARCH_INTERNAL_ITERATIVE_DEEPENING_SCORE_MARGIN 256
#endif

// [2, 8]
#ifndef SEARCH_INTERNAL_ITERATIVE_DEEPENING_PV_NODE_DEPTH_DELTA
#define SEARCH_INTERNAL_ITERATIVE_DEEPENING_PV_NODE_DEPTH_DELTA 4 // 2 * OnePly
#endif

// [0, 1024]
#ifndef SEARCH_INTERNAL_ITERATIVE_DEEPENING_NON_PV_DEPTH_SCALE
#define SEARCH_INTERNAL_ITERATIVE_DEEPENING_NON_PV_DEPTH_SCALE 512 // 0.5 * FLOAT_SCALE
#endif

// [2, 32]
#ifndef SEARCH_SINGULAR_EXTENSION_DEPTH_THRESHOLD
#define SEARCH_SINGULAR_EXTENSION_DEPTH_THRESHOLD 16 // 8 * OnePly
#endif

// [2, 12]
#ifndef SEARCH_SINGULAR_EXTENSION_TTE_DEPTH_THRESHOLD
#define SEARCH_SINGULAR_EXTENSION_TTE_DEPTH_THRESHOLD 6 // 3 * OnePly
#endif

// [0, 1024]
#ifndef SEARCH_SINGULAR_EXTENSION_NULL_WINDOW_SEARCH_DEPTH_SCALE
#define SEARCH_SINGULAR_EXTENSION_NULL_WINDOW_SEARCH_DEPTH_SCALE 512 // 0.5 * FLOAT_SCALE
#endif

// [0, 614]
#ifndef SEARCH_FUTILITY_MOVE_COUNTS_SCALE
#define SEARCH_FUTILITY_MOVE_COUNTS_SCALE 307 // 0.3 * FLOAT_SCALE
#endif

// [1024, 3686]
#ifndef SEARCH_FUTILITY_MOVE_COUNTS_POWER
#define SEARCH_FUTILITY_MOVE_COUNTS_POWER 1843 // 1.8 * FLOAT_SCALE
#endif

// [0, 6146]
#ifndef SEARCH_FUTILITY_MOVE_COUNTS_INTERCEPT
#define SEARCH_FUTILITY_MOVE_COUNTS_INTERCEPT 3073 // 3.001 * FLOAT_SCALE
#endif

// [0, 682]
#ifndef SEARCH_FUTILITY_PRUNING_PV_REDUCTION_SLOPE
#define SEARCH_FUTILITY_PRUNING_PV_REDUCTION_SLOPE 341 // 1.0 / 3.0 * FLOAT_SCALE
#endif

// [0, 256]
#ifndef SEARCH_FUTILITY_PRUNING_PV_REDUCTION_INTERCEPT
#define SEARCH_FUTILITY_PRUNING_PV_REDUCTION_INTERCEPT 128 // 0.25 * FLOAT_SCALE
#endif

// [0, 910]
#ifndef SEARCH_FUTILITY_PRUNING_NON_PV_REDUCTION_SLOPE
#define SEARCH_FUTILITY_PRUNING_NON_PV_REDUCTION_SLOPE 455 // 1.0 / 2.25 * FLOAT_SCALE
#endif

// [0, 682]
#ifndef SEARCH_FUTILITY_PRUNING_NON_PV_REDUCTION_INTERCEPT
#define SEARCH_FUTILITY_PRUNING_NON_PV_REDUCTION_INTERCEPT 337 // 0.33 * FLOAT_SCALE
#endif

// [0, 4096]
#ifndef SEARCH_FUTILITY_PRUNING_SCORE_GAIN_SLOPE
#define SEARCH_FUTILITY_PRUNING_SCORE_GAIN_SLOPE 2048 // 2 * FLOAT_SCALE
#endif

// [2, 16]
#ifndef SEARCH_FUTILITY_PRUNING_PREDICTED_DEPTH_THRESHOLD
#define SEARCH_FUTILITY_PRUNING_PREDICTED_DEPTH_THRESHOLD 8 // 4 * OnePly
#endif

// [2, 12]
#ifndef SEARCH_LATE_MOVE_REDUCTION_DEPTH_THRESHOLD
#define SEARCH_LATE_MOVE_REDUCTION_DEPTH_THRESHOLD 6 // 3 * OnePly
#endif

#endif
